name: movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  equatable: ^2.0.7
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  visibility_detector: ^0.4.0+2
  youtube_player_flutter: ^9.1.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
  go_router: ^14.8.1
  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/images/google_logo.png
    - lib/assets/images/haerin_logo.png