// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE18AhexMdU8PLz-P629rLxm4uS13Xjrk',
    appId: '1:6445395428:web:f1ea5bba5cbafbef802bf1',
    messagingSenderId: '6445395428',
    projectId: 'lumiere-1e344',
    authDomain: 'lumiere-1e344.firebaseapp.com',
    storageBucket: 'lumiere-1e344.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGjjyvKOHck9CT6czg41vieUmpdH3GmIE',
    appId: '1:6445395428:android:74fe5bdb4c290f4b802bf1',
    messagingSenderId: '6445395428',
    projectId: 'lumiere-1e344',
    storageBucket: 'lumiere-1e344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzn__DUqqH99Q3133FpJszAE8TyBsbcYo',
    appId: '1:6445395428:ios:ade79e3bf9e3239f802bf1',
    messagingSenderId: '6445395428',
    projectId: 'lumiere-1e344',
    storageBucket: 'lumiere-1e344.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );
}
